apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xf3tdikpl-go
  janus-idp.io/tekton: xf3tdikpl-go
  backstage.io/kubernetes-id: xf3tdikpl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xf3tdikpl-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
